package vista;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import javax.swing.JDesktopPane;

/**
 *
 * @author Bryan
 */
public class frmMenu extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;

    public frmMenu() {

        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sastreria Ruben");
        this.setLayout(null);
        jMenuItem17_cerrar_sesion.setMargin(new Insets(10, 10, 10, 10));

        jDesktopPane_menu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_nuevo_usuario = new javax.swing.JMenuItem();
        jMenuItem2_gestionar_usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3_nuevo_producto = new javax.swing.JMenuItem();
        jMenuItem4_gestionar_producto = new javax.swing.JMenuItem();
        jMenuItem5_actualizar_stock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6_nuevo_cliente = new javax.swing.JMenuItem();
        jMenuItem7_gestionar_cliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8_nueva_categoria = new javax.swing.JMenuItem();
        jMenuItem9_gestionar_categoria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10_nueva_venta = new javax.swing.JMenuItem();
        jMenuItem11_gestionar_venta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12_reporte_clientes = new javax.swing.JMenuItem();
        jMenuItem13_reporte_categorias = new javax.swing.JMenuItem();
        jMenuItem14_reporte_productos = new javax.swing.JMenuItem();
        jMenuItem15_reporte_ventas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem16_ver_historial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem17_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/file usuario1.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(130, 50));

        jMenuItem1_nuevo_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem1_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevousuariof.jpg"))); // NOI18N
        jMenuItem1_nuevo_usuario.setText("Nuevo usuario");
        jMenu1.add(jMenuItem1_nuevo_usuario);

        jMenuItem2_gestionar_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem2_gestionar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gestionarusuario.jpg"))); // NOI18N
        jMenuItem2_gestionar_usuario.setText("Gestionar usuarios");
        jMenu1.add(jMenuItem2_gestionar_usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/file producto.jpg"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem3_nuevo_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem3_nuevo_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevopr.jpg"))); // NOI18N
        jMenuItem3_nuevo_producto.setText("Nuevo producto");
        jMenuItem3_nuevo_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_nuevo_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3_nuevo_producto);

        jMenuItem4_gestionar_producto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem4_gestionar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gestionarproduct.jpg"))); // NOI18N
        jMenuItem4_gestionar_producto.setText("Gestionar producto");
        jMenuItem4_gestionar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_gestionar_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4_gestionar_producto);

        jMenuItem5_actualizar_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem5_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/actualizarproduct.jpg"))); // NOI18N
        jMenuItem5_actualizar_stock.setText("Actualizar stock");
        jMenuItem5_actualizar_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_actualizar_stockActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5_actualizar_stock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fileclientes.jpg"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(130, 50));

        jMenuItem6_nuevo_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem6_nuevo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevoclientef.jpg"))); // NOI18N
        jMenuItem6_nuevo_cliente.setText("Nuevo cliente");
        jMenuItem6_nuevo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6_nuevo_clienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6_nuevo_cliente);

        jMenuItem7_gestionar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem7_gestionar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gestionarclient.jpg"))); // NOI18N
        jMenuItem7_gestionar_cliente.setText("Gestionar Cliente");
        jMenuItem7_gestionar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_gestionar_clienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7_gestionar_cliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/filecategoriaa.jpg"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem8_nueva_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem8_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevacateg.jpg"))); // NOI18N
        jMenuItem8_nueva_categoria.setText("Nueva categoria");
        jMenuItem8_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_nueva_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8_nueva_categoria);

        jMenuItem9_gestionar_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem9_gestionar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gestionarcategoria.jpg"))); // NOI18N
        jMenuItem9_gestionar_categoria.setText("Gestionar categoria");
        jMenuItem9_gestionar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_gestionar_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9_gestionar_categoria);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/filefactura.jpg"))); // NOI18N
        jMenu5.setText("Facturar");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem10_nueva_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem10_nueva_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevaventa.jpg"))); // NOI18N
        jMenuItem10_nueva_venta.setText("Nueva venta");
        jMenu5.add(jMenuItem10_nueva_venta);

        jMenuItem11_gestionar_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem11_gestionar_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gestionarventas.jpg"))); // NOI18N
        jMenuItem11_gestionar_venta.setText("Gestionar  ventas");
        jMenu5.add(jMenuItem11_gestionar_venta);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/filereporte.jpg"))); // NOI18N
        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem12_reporte_clientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem12_reporte_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportestodo.jpg"))); // NOI18N
        jMenuItem12_reporte_clientes.setText("Reporte clientes");
        jMenu6.add(jMenuItem12_reporte_clientes);

        jMenuItem13_reporte_categorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem13_reporte_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportestodo.jpg"))); // NOI18N
        jMenuItem13_reporte_categorias.setText("Reporte categorias");
        jMenu6.add(jMenuItem13_reporte_categorias);

        jMenuItem14_reporte_productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem14_reporte_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportestodo.jpg"))); // NOI18N
        jMenuItem14_reporte_productos.setText("Reporte productos");
        jMenu6.add(jMenuItem14_reporte_productos);

        jMenuItem15_reporte_ventas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem15_reporte_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reportestodo.jpg"))); // NOI18N
        jMenuItem15_reporte_ventas.setText("Reporte ventas");
        jMenu6.add(jMenuItem15_reporte_ventas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/filehistorial.jpg"))); // NOI18N
        jMenu7.setText("Historial");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(130, 50));

        jMenuItem16_ver_historial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem16_ver_historial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/historialm.jpg"))); // NOI18N
        jMenuItem16_ver_historial.setText("Ver historial");
        jMenu7.add(jMenuItem16_ver_historial);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/filecerrarsesion.jpg"))); // NOI18N
        jMenu8.setText("Cerrar sesión");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setMaximumSize(new java.awt.Dimension(190, 32767));
        jMenu8.setMinimumSize(new java.awt.Dimension(200, 50));
        jMenu8.setPreferredSize(new java.awt.Dimension(190, 50));

        jMenuItem17_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem17_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrarsesionmenu.jpg"))); // NOI18N
        jMenuItem17_cerrar_sesion.setText("Cerrar ");
        jMenuItem17_cerrar_sesion.setPreferredSize(new java.awt.Dimension(120, 22));
        jMenuItem17_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17_cerrar_sesionActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17_cerrar_sesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5_actualizar_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_actualizar_stockActionPerformed
        FrActualizarStock fractualizarstock = new FrActualizarStock();
        jDesktopPane_menu.add(fractualizarstock);
        fractualizarstock.setVisible(true);
    }//GEN-LAST:event_jMenuItem5_actualizar_stockActionPerformed

    private void jMenuItem8_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_nueva_categoriaActionPerformed
        FrCategoria frCategoria = new FrCategoria();
        jDesktopPane_menu.add(frCategoria);
        frCategoria.setVisible(true);


    }//GEN-LAST:event_jMenuItem8_nueva_categoriaActionPerformed

    private void jMenuItem9_gestionar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_gestionar_categoriaActionPerformed
        FrGestionarCategoria frgestionarcategoria = new FrGestionarCategoria();
        jDesktopPane_menu.add(frgestionarcategoria);
        frgestionarcategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem9_gestionar_categoriaActionPerformed

    private void jMenuItem3_nuevo_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_nuevo_productoActionPerformed
        FrProducto frproducto = new FrProducto();
        jDesktopPane_menu.add(frproducto);
        frproducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem3_nuevo_productoActionPerformed

    private void jMenuItem4_gestionar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_gestionar_productoActionPerformed
        FrGestionarProducto frgestionarproducto = new FrGestionarProducto();
        jDesktopPane_menu.add(frgestionarproducto);
        frgestionarproducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem4_gestionar_productoActionPerformed

    private void jMenuItem6_nuevo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6_nuevo_clienteActionPerformed
        FrCliente frcliente = new FrCliente();
        jDesktopPane_menu.add(frcliente);
        frcliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem6_nuevo_clienteActionPerformed

    private void jMenuItem7_gestionar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_gestionar_clienteActionPerformed
        FrGestionarCliente frgestionarcliente = new FrGestionarCliente();
        jDesktopPane_menu.add(frgestionarcliente);
        frgestionarcliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem7_gestionar_clienteActionPerformed

    private void jMenuItem17_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17_cerrar_sesionActionPerformed

        Frmlogin frmlogin = new Frmlogin();
        frmlogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem17_cerrar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10_nueva_venta;
    private javax.swing.JMenuItem jMenuItem11_gestionar_venta;
    private javax.swing.JMenuItem jMenuItem12_reporte_clientes;
    private javax.swing.JMenuItem jMenuItem13_reporte_categorias;
    private javax.swing.JMenuItem jMenuItem14_reporte_productos;
    private javax.swing.JMenuItem jMenuItem15_reporte_ventas;
    private javax.swing.JMenuItem jMenuItem16_ver_historial;
    private javax.swing.JMenuItem jMenuItem17_cerrar_sesion;
    private javax.swing.JMenuItem jMenuItem1_nuevo_usuario;
    private javax.swing.JMenuItem jMenuItem2_gestionar_usuario;
    private javax.swing.JMenuItem jMenuItem3_nuevo_producto;
    private javax.swing.JMenuItem jMenuItem4_gestionar_producto;
    private javax.swing.JMenuItem jMenuItem5_actualizar_stock;
    private javax.swing.JMenuItem jMenuItem6_nuevo_cliente;
    private javax.swing.JMenuItem jMenuItem7_gestionar_cliente;
    private javax.swing.JMenuItem jMenuItem8_nueva_categoria;
    private javax.swing.JMenuItem jMenuItem9_gestionar_categoria;
    // End of variables declaration//GEN-END:variables
}
